authors:
  - Chen Sagi (@chensagi)
  - Michal Greenberg (@micahlg)
  - Magesh Karunakaran (@radwaremageshk)
  - Topaz Avraham (@topaza)
dependencies: {}
description: A collection of Ansible Modules for Radware devices
documentation: ''
homepage: https://www.radware.com
issues: https://github.com/Radware/radware_alteon_modules/issues
license_file: 'COPYING'
name: radware_alteon
namespace: radware
readme: README.md
repository: https://github.com/Radware/radware_alteon_modules
tags:
  - radware
  - alteon
  - cloud
  - collection
  - networking
  - sdn
version: 1.1.0
